server:
  port: 9100
  servlet:
    context-path: /
  ssl:
    enabled: false

spring:
  application:
    name: dream-home-common
  profiles:
    active: dev
  devtools:
    livereload:
      port: 39100

#  redis:
#    timeout: 6000ms
#    password: '12345678'
#    cluster:
#      max-redirects: 3  # 获取失败 最大重定向次数
#      nodes:
#        - localhost:7000
#        - localhost:7001
#        - localhost:7002
#        - localhost:7003
#        - localhost:7004
#        - localhost:7005
#    lettuce:
#      pool:
#        max-active: 1000  #连接池最大连接数（使用负值表示没有限制）
#        max-idle: 10 # 连接池中的最大空闲连接
#        min-idle: 5 # 连接池中的最小空闲连接
#        max-wait: 5000ms # 连接池最大阻塞等待时间（使用负值表示没有限制）

#  data:
#    elasticsearch:
#      host: 10.105.146.34
#      port: 9200

management:
  endpoints:
    web:
      exposure:
        include: "*"
  server:
    port: 9100
    servlet:
      context-path: /
    ssl:
      enabled: false
  endpoint:
    health:
      show-details: always


